name: Docker Image CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Docker Tag
      run: echo "docker_tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ env.docker_tag }}

    - name: Verify Docker image locally
      run: docker images --format '{{.Repository}}:{{.Tag}}' | grep ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ env.docker_tag }}

  push:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image with release tag
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.event.release.tag_name }}

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.event.release.tag_name }}

    - name: Verify Docker image on Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.event.release.tag_name }}
        docker inspect ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:${{ github.event.release.tag_name }}
